server:
  port: 8500
  servlet:
    context-path: /

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

openai-service:
  api-key: ${OPENAI_API_KEY}
  gpt-model: gpt-3.5-turbo
  audio-model: whisper-1
  http-client:
    read-timeout: 3000
    connect-timeout: 3000
  urls:
    base-url: https://api.openai.com/v1
    chat-url: /chat/completions
    create-transcription-url: /audio/transcriptions

logging:
  level:
    com.github.kolomolo.service.openaiclient: DEBUG
    feign: DEBUG


management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: 'ALWAYS'
  health:
    circuitbreakers:
      enabled: true

jwt:
  secret-key: ${JWT_SECRET_KEY:9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c6b5d8e9f7a}
  username: ${JWT_USERNAME:devuser}
  password: ${JWT_PASSWORD:devpass123}
  expiration-ms: 86400000  # 24 hours in milliseconds
  issuer: kolomolo-service}